import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./components/providers";
import Appbar from "./components/Appbar";
import SignInPanel from "./components/signInPanel";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Appbar>
            <SignInPanel />
          </Appbar>
          
          {children}
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}



/*
import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Providers } from "./components/providers"
import Appbar from "./components/AppBar"
import SignInPanel from "./components/signInPanel"
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Real Estate Platform",
  description: "Find your dream property",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // Get authentication status on the server
  const { getUser } = getKindeServerSession()
  const user = await getUser()

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* AppBar will handle its own visibility based on auth state *}
          <Appbar>
            <SignInPanel />
          </Appbar>

          {/* If user is not authenticated, show a login prompt *}
          {!user && (
            <div className="flex justify-center items-center p-4 bg-gradient-to-br from-sky-400 to-indigo-500 text-white">
              <p>
                Please{" "}
                <a href="/api/auth/login" className="underline font-bold">
                  sign in
                </a>{" "}
                to access all features
              </p>
            </div>
          )}

          {children}
          <ToastContainer />
        </Providers>
      </body>
    </html>
  )
}

*/